Microverse Project Responsive Web: The Next Web
jcy2704/thenextweb pull request #1
Opened 2020-09-28 15:25 UTC by Janluc

## The Next Web

- Use of Media Queries for a responsive website

- Use of Flexbox and Grid for the general layout of the website

- Use of semantic HTML for further readability

2020-09-28 17:14 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hi Team!!! Great effort on the project!

:100: Descriptive README
:100: Descriptive enough PULL REQUEST and commit messages.
:100: Using semantic HTML

There are still some issues to be addressed.

# Required Changes
### [Mandatory] :red_circle: 

- [x] nav should be wrapped around the ```<header>``` HTML tag. See comments.

- [x] Assignt alternative text to all images. Don't leave it blank. See inline comments.

- [x] Footer social media elements should be links

- [x] Footer menu elements should be links

#### Mobile

- [x] Extra margin on mobile version
![image](https://user-images.githubusercontent.com/25774518/94459219-aaea8200-017c-11eb-95f7-26c5efae1a24.png)

- [x] Images not displaying as the original
![image](https://user-images.githubusercontent.com/25774518/94459526-16ccea80-017d-11eb-93f1-3f12c938d865.png)

- [x] Articles doesn't have the right amount of margin between them in Latest News and Latest Deals
![image](https://user-images.githubusercontent.com/25774518/94459629-3d8b2100-017d-11eb-86d3-71e7137c9c98.png)

- [x] Text is missing surrounding white space
![image](https://user-images.githubusercontent.com/25774518/94459726-627f9400-017d-11eb-8f64-d5d29b6d2313.png)

- [x] Missing arrow
![image](https://user-images.githubusercontent.com/25774518/94459896-9490f600-017d-11eb-8aa0-6e605b61707a.png)

- [x] Footer menu not resizing properly
![image](https://user-images.githubusercontent.com/25774518/94461990-7678c500-0180-11eb-8271-b210be5dfee2.png)

- [x]  Latest findings not displaying properly
![image](https://user-images.githubusercontent.com/25774518/94461915-61039b00-0180-11eb-92dd-5830f42a434c.png)


#### Tablet (768)

- [x] Navbar is not displaying as original in tablet mode
![image](https://user-images.githubusercontent.com/25774518/94461546-e0dd3580-017f-11eb-8fbf-14ef2b03b3fe.png)


- [x] footer menu not resizing as original
![image](https://user-images.githubusercontent.com/25774518/94461710-1bdf6900-0180-11eb-8c24-7eb5c2ab1711.png)

#### Desktop (1024)

- [ ] Navbar does not match original
![image](https://user-images.githubusercontent.com/25774518/94461165-614f6680-017f-11eb-9ff0-e889ebf909ca.png)

### [OPTIONAL]  :large_blue_circle: 

- [ ] It would be interesting to try background images using the background CSS property for all images. If you may try this out.

- [ ] Keep the CSS files DRY. See inline comments.

### [Comments] :green_circle: 
- The ```<header>``` element represents a container for introductory content or a **set of navigational links**.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-28 17:20 UTC, jubaan requested changes

2020-09-28 17:20 UTC, jubaan commented on css/tablet.css
> +
- [ ] Keep code DRY. Example:
**Actual**
```
.ham-menu {
  display: none;
}

.nav-hid {
  display: none;
}
```
**Improved*** :+1: :
```
.ham-menu,
.nav-hid {
  display: none;
}
```

2020-09-28 17:20 UTC, jubaan commented on index.html
> +                    alt="">
- [ ] Fill the ```alt=""``` attribute.

2020-09-28 17:20 UTC, jubaan commented on index.html
> +      </ul>
- [ ] This elements should be links

2020-09-28 20:31 UTC, jcy2704 commented
@jubaan In the desktop resolution. Do you want the navbar to look like when we are at the top, or do you want it to look like when we scroll a little bit to the bottom?

2020-09-28 23:17 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Great job on implementing the requested changes. However, there are still more required changes before the project can be approved.**

## Mandatory

#### 1).  @1024px width

- **Fix the middle navbar so the text doesn't display on multiple lines. (see screenshot below).**

- **Remove the left spacing of the text in the yellow background. (see screenshot below).**

original  |  clone
--------- |  -------
![web_original](https://user-images.githubusercontent.com/38922385/94492407-eaec4c00-01f2-11eb-9ca7-2b38c3394ca6.png)  |  ![web_clone](https://user-images.githubusercontent.com/38922385/94492445-ff304900-01f2-11eb-9f55-e1bc2c469ca6.png)

#### 2). @1023px width

- **The top images have a bigger height than the original.**

original  |  clone
--------- |  ---------
![top_original](https://user-images.githubusercontent.com/38922385/94493222-b8dbe980-01f4-11eb-8b12-1fc4231cbcf1.png)  |  ![top_clone](https://user-images.githubusercontent.com/38922385/94493243-c5f8d880-01f4-11eb-994f-b7ae8fcda3f3.png)

- **The sub-topics below latest funding rounds should display on one line and not multiple lines.**

original | clone
---------| -------
![latest_original](https://user-images.githubusercontent.com/38922385/94493552-95fe0500-01f5-11eb-9b9b-5a87185037b0.png) | ![latest_clone](https://user-images.githubusercontent.com/38922385/94493579-a615e480-01f5-11eb-875e-4eba66299c04.png)

3). **The medium breakpoint is at 768px  and not 760px. Please update that.**
![breakpoint](https://user-images.githubusercontent.com/38922385/94493889-87fcb400-01f6-11eb-8762-0f5ec5667450.png)

#### 4). @759px width

- **Increase the image heights for all sections starting at Hard fork and ending at distract, so they match the original. Here is an example of the Hardfork section.**

original | clone
---------| -------
![hardfork_original](https://user-images.githubusercontent.com/38922385/94494328-9a2b2200-01f7-11eb-8532-455b88c02365.png)  | ![hardfork_clone](https://user-images.githubusercontent.com/38922385/94494360-aadb9800-01f7-11eb-9e6f-137dd2d6c7c1.png)

 5). **In the latest deals section, the small text below the image captions should be a price, not time.**

original | clone
---------| -------
![deals_original](https://user-images.githubusercontent.com/38922385/94495006-415c8900-01f9-11eb-89b9-7aec15bc6b06.png) |  ![deals_clone](https://user-images.githubusercontent.com/38922385/94495074-779a0880-01f9-11eb-8355-5014b8cd2113.png)

2020-09-28 23:47 UTC, jcy2704 commented
Hello, @blackpintz thanks for the code review. However, in point number 2 there seems to be something wrong because on my screen with the same resolution on both websites are almost the same.
**Original**
![Original](https://user-images.githubusercontent.com/64392568/94496743-d8eeb700-01ba-11eb-91fd-4d979c64984c.png)
**Clone**
![Clone](https://user-images.githubusercontent.com/64392568/94496766-e99f2d00-01ba-11eb-81cc-1cd46d72112f.png)

2020-09-29 00:40 UTC, jubaan commented
> @jubaan In the desktop resolution. Do you want the navbar to look like when we are at the top, or do you want it to look like when we scroll a little bit to the bottom?

I'm just reading this message @jcy2704, I don't like Github notifications a lot of noise and messages like this pass inadvertent. Please next time don't hesitate on reaching me on slack, you can find me like @jubaan 

The idea is to have a navbar as similar to the original in both scenarios at the top and after scrolling., But if it's out of the scope of the programmer, and the project, because maybe doing so requires a technology that is not required like JS, it should match the navbar look and style at the start position.

2020-09-29 00:45 UTC, jubaan requested changes
# Status: Changes Required :recycle:

Great work working on the previously required changes.

- [ ]  Please update the live preview link in the README file. The live preview still shows the version without changes.

### [COMMENTS] :green_circle: 
- The README besides the project is one of the most important files of the project. It gives the reader a summary of the programmer's intent. We should maintain the file updated to reflect the latest changes, doing so helps to avoid confusion and misleading.

2020-09-29 00:54 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## :clap: :clap: :clap: Awesome team! Congrats on finishing another project! 

You may now merge your project to master!

## See you at the top :rocket: !!

2020-09-29 01:08 UTC, merged